name: doangiuaki_ppptpmhdt # Bạn có thể giữ tên project của bạn
description: A new Flutter project.

# Ngăn việc vô tình publish lên pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Phiên bản của ứng dụng
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Yêu cầu phiên bản Dart 3.0.0 trở lên

#
# === PHẦN DEPENDENCIES ===
# Đây là các gói mà ứng dụng của bạn cần để chạy
#
dependencies:
  flutter:
    sdk: flutter

  # Mặc định của Flutter
  cupertino_icons: ^1.0.2

  # 1. Gọi API
  http: ^1.1.0

  # 2. Quản lý trạng thái (cho AuthService, ThemeProvider, ActivityService)
  provider: ^6.0.5

  # 3. Lưu trữ local (lưu token đăng nhập, lưu cài đặt theme)
  shared_preferences: ^2.2.2

  # 4. Giải mã JWT (để lấy user role từ token)
  jwt_decode: ^0.3.1

  # 5. Tạo mã QR (cho Admin)
  qr_flutter: ^4.1.0

  # 6. Quét mã QR (cho Student - bạn đã có file qr_scanner_screen.dart)
  mobile_scanner: ^3.5.6 # (Hoặc ^4.0.0 tùy bạn)

  # 7. Định dạng ngày tháng (dùng trong activity_form.dart)
  intl: ^0.20.2


#
# === PHẦN DEV DEPENDENCIES ===
# Các gói này chỉ dùng cho việc phát triển và viết test
#
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Gói lint để kiểm tra chất lượng code
  flutter_lints: ^2.0.0

# Cấu hình chung của Flutter
flutter:

  # Bật cờ use-material-design (sử dụng Material 3)
  uses-material-design: true

  # Nếu bạn có thêm hình ảnh, bạn sẽ khai báo ở đây
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Nếu bạn có thêm font chữ tùy chỉnh, bạn sẽ khai báo ở đây
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic